# Production Docker Compose configuration
# This extends the base docker-compose.yml with production-specific settings

version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ai_product_studio_prod}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    volumes:
      - redis_data_prod:/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  app:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      restart_policy:
        condition: unless-stopped
        delay: 10s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data_prod:
    driver: local
  redis_data_prod:
    driver: local